# Scenario & Assets Agent Configuration
# Phase 1: Hardcoded configuration without LLM integration

# Scene selection mode
# Options: "auto" (automatic selection based on objects), or specific scene name
# Available scenes: kitchen_0, kitchen_1, kitchen_2, living_room_0, studyroom_0, 
#                  bedroom_0, office_0, lab_0, lab_1, etc.
scenario_name: "auto"

# Background texture (optional)
# Examples: "parquet_floor", "floor1", "floor2", etc.
background_texture: "parquet_floor"

# Object classes to include in the scene
# This list determines which objects will be placed in the scene
# Phase 1: Using simple object types from VLABench constant.py
object_classes: 
  - "fruit"  # Non-container object for pick-and-place task

# Container requirement for pick-and-place tasks
# If true and no container in object_classes, will auto-add a default container
requires_container: true

# External API settings (Phase 1: disabled)
external_api:
  tripo_ai:
    enabled: false
    prompt: "A modern, minimalist kitchen."