# Trajectory Generation Agent Configuration
# Phase 1: Basic trajectory generation without complex features

# Simulation parameters
simulation_steps: 1000
num_episodes: 1  # Reduced for faster testing

# Output configuration
output_dir: "VLABench/trajectories"

# Robot configuration
robot: "franka"  # Options: "franka", "ur5", etc.

# Human-in-the-loop settings
enable_human_in_loop: false  # Set to true to pause for human approval

# Generation parameters
record_video: true
save_format: "hdf5"  # Options: "hdf5", "rlds"
max_episode: 100
early_stop: false  # Stop if a skill fails during generation

# Timeout settings (in seconds)
timeout: 300  # 5 minutes timeout for trajectory generation

# Debug settings
debug: false
verbose: true

# Phase 1 specific settings
use_dummy_trajectory: true  # Create dummy files when script is not available

# Advanced settings (Phase 2+)
eval_unseen: false  # Evaluate on unseen object categories
parallel_generation: false  # Generate multiple trajectories in parallel
retry_on_failure: false  # Retry if generation fails
max_retries: 3