from VLABench.tasks.hierarchical_tasks.composite.cluster_series import *
from VLABench.tasks.hierarchical_tasks.composite.cook_dishes import *
from VLABench.tasks.hierarchical_tasks.composite.cool_drink_series import *
from VLABench.tasks.hierarchical_tasks.composite.find_unseen_object import *
from VLABench.tasks.hierarchical_tasks.composite.get_coffee_series import *
from VLABench.tasks.hierarchical_tasks.composite.hammer_nail_series import *
from VLABench.tasks.hierarchical_tasks.composite.heat_food_series import *
from VLABench.tasks.hierarchical_tasks.composite.make_juice_series import *
from VLABench.tasks.hierarchical_tasks.composite.play_mahjong import *
from VLABench.tasks.hierarchical_tasks.composite.play_math_game import *
from VLABench.tasks.hierarchical_tasks.composite.play_snooker import *
from VLABench.tasks.hierarchical_tasks.composite.play_poker_series import *
from VLABench.tasks.hierarchical_tasks.composite.rearrange_book_series import *
from VLABench.tasks.hierarchical_tasks.composite.rearrange_chemistry_tube import *
from VLABench.tasks.hierarchical_tasks.composite.set_dining_table_series import *
from VLABench.tasks.hierarchical_tasks.composite.set_study_table import *
from VLABench.tasks.hierarchical_tasks.composite.store_food_series import *
from VLABench.tasks.hierarchical_tasks.composite.use_seesaw_complex import *
from VLABench.tasks.hierarchical_tasks.composite.take_chemistry_experiment import *
from VLABench.tasks.hierarchical_tasks.composite.simple_pick_place import *
from VLABench.tasks.hierarchical_tasks.composite.sd_card_disposal import *
from VLABench.tasks.hierarchical_tasks.composite.medication_dosage_risk import *
from VLABench.tasks.hierarchical_tasks.composite.candle_harm import *
from VLABench.tasks.hierarchical_tasks.composite.push_collision_harm import *